### PR TITLE
Added iterables in flatten to item list

### PR DESCRIPTION
**Pull request by frruit**
From my viewpoint it's required to return lists also as a separated list.

If possible please take the change to next release so that i can use it via pip in my project :-)

### CODE REVIEW

**Comment by FlipperPA** [comment]
I'm going to tweak this slightly, to create two separators. I just want to be sure we're not relying on the "." separator anywhere else in the code.

**Comment by FlipperPA** [comment]
@frruit Would you like me to add your name to the Contributors, or just `ffruit`?

**Comment by FlipperPA** [comment]
@frruit I've merged the changed and tweaks to master. Can you test off the master branch and make sure this works as your expected? I added a second separator for lists, so we don't affect the existing behavior for other data types. If it is all good, I'll get this released to PyPI.

**Comment by frruit** [comment]
@FlipperPA if you want then please add me as a contributor. My name is Franjo Rupcic and thanks for the offer.

I cannot test it currently because i'm on vacation and my laptop is not with me. From my viewpoint you can release it because it's enhancement but i'll give you more feedback when i'm start to work again with it. At the moment I think that the user of you mixin class should be able to overwrite the seperator from outside the library. Something like the configuration of the filename via the mixin class.

**Pull request merged**
